Repository xmidt-org/webpa-common, pull requests merged in 2020-10, with the labels that each got.

#521 Add default for pprof server
  CHANGELOG.md
  server/viper.go
Labels: enhancement

#525 bumped bascule and consul versions
  CHANGELOG.md
  basculechecks/capabilitiesvalidator.go
  basculechecks/capabilitiesvalidator_test.go
  basculechecks/metricvalidator.go
  basculechecks/metricvalidator_test.go
  go.mod
  go.sum
Labels: enhancement, hacktoberfest

#528 New webhook service
  go.mod
  go.sum
  xwebhook/endpoint.go
  xwebhook/handler.go
  xwebhook/metrics.go
  xwebhook/mocks_test.go
  xwebhook/service.go
  xwebhook/store.go
  xwebhook/transport.go
  xwebhook/watch.go
  xwebhook/webhook.go
Labels: road-to-argus

#534 obfuscate secrets
  CHANGELOG.md
  xwebhook/transport.go
Labels: road-to-argus

#533 Add fallback method to fetching a client's ID
  CHANGELOG.md
  xwebhook/transport.go
Labels: road-to-argus
