Repository xmidt-org/webpa-common, pull requests merged in 2020-04, with the labels that each got.

#462 Abandon racy testLogger using testing.T or testing.B
  .gitignore
  .travis.yml
  CHANGELOG.md
  logging/testLogger.go
  logging/testLogger_test.go
Labels: bug

#469 modify webhooks package to not use logging package functions
  CHANGELOG.md
  webhook/aws/sns.go
Labels: bug, performance

#447 Device Metadata
  .gitignore
  CHANGELOG.md
  device/context.go
  device/device.go
  device/device_test.go
  device/handlers.go
  device/manager.go
  device/metadata.go
  device/metadata_test.go
  device/mocks.go
  go.mod
  go.sum
Labels: partner-id
